services:
  Nng\Nnhelpers\EventListener\ClearCacheEvent:
    tags:
      - name: event.listener
        method: handleEvent
        identifier: 'myListener'
        before: 'redirects, anotherIdentifier'
        event: TYPO3\CMS\Core\Cache\Event\CacheFlushEvent

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Nng\Nnhelpers\:
    resource: '../Classes/*'
    exclude: 
      - '../Classes/Domain/Model/*'
      - '../Classes/aliases.php'
      - '../Classes/nnhelpers.php'

  Nng\Nnhelpers\Controller\ModuleController:
    tags: ['backend.controller']

  Nng\Nnhelpers\Middleware\:
    resource: '../Classes/Middleware/*'
    autowire: true
    autoconfigure: true
    public: true